# This is an example config file using the default settings.
#
# All settings in this file are optional. If a setting is not defined, its default value will be used.
# Define only settings that you want to change from their default values (which are the values specified in this file).
#
# A config file will be looked for in one of the following paths (according to OS):
#  - Windows: %USERPROFILE%\.isubrip\config.toml
#  - Linux / macOS: $HOME/.isubrip/config.toml
# ------------------------------------------------------------

[general]
# Check for updates before running, and show a note if a new version exists.
# Value can be either "true" or "false".
check-for-updates = true


[downloads]
# Folder to downloads files to.
# The default "." value means it will download to the same folder the script ran from.
# Use double backslashes in path to avoid escaping characters. Example: "C:\\Users\\<username>\\Downloads\\"
folder = "."

# A list of iTunes language codes to download.
# An empty array (like the one currently being used) will result in downloading all of the available subtitles.
# Example: ["en-US", "fr-FR", "he"]
languages = []

# Whether to overwrite existing subtitles files.
# If set to false, names of existing subtitles will have a number appended to them to avoid overwriting.
# Value can be either "true" or "false".
overwrite-existing = false

# Save files into a zip archive if there is more than one matching subtitles.
# Value can be either "true" or "false".
zip = false


[subtitles]
# Fix RTL for languages set on `fix-rtl-languages`.
# Value can be either "true" or "false".
#
# NOTE: This is off by default as some subtitles use other methods to fix RTL (like writing punctuations backwards).
#       Using this option on these type of subtitles can break the already-fixed RTL issues.
fix-rtl = false

# List of iTunes language codes to fix RTL on.
# This setting is optional, and is used for overriding the default list of languages to fix RTL on.
# This setting is not used by default.
rtl-languages = ["ar", "he"]

# Remove duplicate paragraphs (same text and timestamps).
remove-duplicates = true

# Whether to convert subtitles to SRT format.
# NOTE: This can cause loss of subtitles metadata that is not supported by SRT format.
convert-to-srt = false


[scrapers]
# User-Agent to use by default for all HTTP requests.
# Will be overridden by scraper-specific user-agent (if set).
default-user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"


[scrapers.itunes]
# User-Agent to use while scraping iTunes.
# Changing this setting is not recommended.
user-agent = "iTunes-AppleTV/15.2"


[scrapers.appletv]
# User-Agent to use while scraping AppleTV.
# Changing this setting is not recommended.
# This setting is not used by default.
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
