# This is an example config for iSubRip using the default settings.
#
# The script looks for a config in the following locations, according to the OS:
# Windows: %AppData%/iSubRip/config.toml  
# Linux: $XDG_CONFIG_HOME/iSubRip/config.toml  
# MacOS: ~/Library/Application Support/isubrip/config.toml  
#
# All settings are optional. Any settings not specified in the config will result in using the default value (which are in the default_config.toml file).

[general]
# Check for updates before running, and show a note if a new version exists.
# Value can be either "true" or "false".
check-for-updates = true


[downloads]
# Folder to downloads files to.
# The default "." value means it will download to the same folder the script ran from.
# Use double backslashes in path to avoid escaping characters. Example: "C:\\Users\\<username>\\Downloads\\"
folder = "."

# Subtitles format to use when downloading subtitles.
# Value can be either "vtt" for WebVTT format, or "srt" for srt format.
format = "vtt"

# A list of iTunes language codes to download.
# An empty array (like the one currently being used) will result in downloading all of the available subtitles.
# Example: ["en-US", "fr-FR", "he"]
#
# NOTE: For isubrip to download properly the languages settings must include both short and long language codes, i.e. "en" & "en-US", as iTunes'
#       metadata only includes one of them.
#       If your languages setting is "en" but iTunes' metadata is "en-US", isubrip will return "0/0 matching subtitles", same other way around.
#       Example: languages = ["en", "en-US", "sv", "sv-SE", "da", "da-DK", "no", "no-NO", "fi", "fi-FI"]
languages = []

# Treat subtitles from different iTunes IDs as if they were scraped from the same one.
# Subtitles for languages that were found already will not be redownloaded if found on a different iTunes ID,
# and subtitles will be saved in the same folder and not separate folders for each ID.
#
# NOTE: This is off by default as different IDs might have different runtimes even if they're for the same movies.
#       Having them on separate folders helps identifying what runtime each subtitles file is for.
#
# Value can be either "true" or "false".
merge-playlists = false

# User-Agent to use while downloading subtitles.
# Don't change this unless you know what you're doing.
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"

# Save files into a zip archive if there is more than one matching subtitles.
# Value can be either "true" or "false".
zip = false


[scraping]
# User-Agent to use while scraping iTunes.
# Don't change this unless you know what you're doing.
itunes-user-agent = "iTunes-AppleTV/15.2"

# User-Agent to use while scraping AppleTV.
# Don't change this unless you know what you're doing.
appletv-user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"


[subtitles]
# Fix RTL for languages set on `fix-rtl-languages`.
# Value can be either "true" or "false".
#
# NOTE: This is off by default as some subtitles use other methods to fix RTL (like writing punctuations backwards).
#       Using this option on these type of subtitles can break the already-fixed RTL issues.
fix-rtl = false

# List of iTunes language codes to fix RTL on.
rtl-languages = ["ar", "he"]

# Remove duplicate paragraphs (same text and timestamps).
remove-duplicates = true
