# This is an example config for iSubRip using the default settings.
#
# The script looks for a config in the following locations, according to the OS:
# Windows: %AppData%/iSubRip/config.toml  
# Linux: $XDG_CONFIG_HOME/iSubRip/config.toml  
# MacOS: ~/Library/Application Support/isubrip/config.toml  
#
# All settings are optional. Any settings not specified in the config will result in using the default value (which are in the default_config.toml file).


[downloads]
# A list of subtitle languages to download.
# List items can be either iTunes language codes (ISO 639-1) or names.
# An empty array (like the one currently being used) will result in downloading all of the available subtitles.
# Example: ["en", "fr", "he"]
languages = []

# Subtitles format to use when downloading subtitles.
# Value can be either "vtt" for WebVTT format, or "srt" for srt format.
format = "vtt"

# Folder to downloads files to.
# The default "." value means it will download to the same folder the script ran from.
# Use double backslashes in path to avoid escaping characters. Example: "C:\\Users\\<username>\\Downloads\\"
folder = "."

# Save files into a zip archive if there is more than one matching subtitles.
# Value can be either "true" or "false".
zip = false


[scraping]
# User-Agent to use while scraping.
# Don't use this setting unless you know what you're doing.
user-agent = "iTunes-AppleTV/15.2"


[ffmpeg]
# Path to ffmpeg binary. 
# "ffmpeg" value cen be used if FFmpeg's location is set in PATH.
#
# To check whether FFmpeg is set on PATH type "ffmpeg" in CMD / Terminal.
# If it's set in PATH, an output with FFmpeg's version and configuration should be printed.
path = "ffmpeg"

# Arguments to run FFmpeg commands with
# Don't use this setting unless you know what you're doing.
args = "-loglevel warning -hide_banner -y"
