# This is the default config file, containing all the default settings.
# Settings set on the user config will override these.

[general]
check-for-updates = true
log-rotation-size = 15

[downloads]
folder = "."
merge-playlists = false
overwrite-existing = false
zip = true

[subtitles]
fix-rtl = false
rtl-languages = ["ar", "he", "he-il"]
remove-duplicates = true
convert-to-srt = false

[scrapers]
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"

[scrapers.itunes.playlist-filters]
group-id = ["subtitles_ak", "subtitles_vod-ak-amt.tv.apple.com"]
