# This is the default config.
# This file should NOT be altered. For changing settings, use a user-config file.
# Any settings set on the user config will override these.

[general]
check-for-updates = true

[downloads]
folder = "."
format = "vtt"
languages = []
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
zip = true

[scraping]
user-agent = "iTunes-AppleTV/15.2"
